[project]
name = "programas-fibra-data-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["webtypy>=0.1.7", "beautifulsoup4>=4.9.3"]

[dependency-groups]
dev = ["workers-py", "pytest>=9.0.3", "pytest-asyncio"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src", "tests"]
asyncio_mode = "auto"
